### ISSUE TITLE
Linux Server CPU usage twice higher than Windows 

### ISSUE THREAD

**Issue by ghost** [broke-protocol/BrokeProtocol#373] opened 2018-01-22 17:02 UTC
Hello. Linux Server appears to have more CPU usage than Windows one.
With 5 people online it's like this:

**- Windows Server 2016: 3% CPU without people** 
https://i.imgur.com/61C4kQd.png 
**- Windows Server 2016: 5% 5 People online**
https://i.imgur.com/UuNgGqT.png

And now Linux
**- Ubuntu about 20% CPU without players**
https://i.imgur.com/aZrkTtq.png
**- Ubuntu over 50% CPU with 5 players**
https://i.imgur.com/87EMEwN.png

All tested on same machine with on a i7 4770k CPU.

Currently my server is barely playable with 2 people because of those lags.
This CPU usage appeared 2 updates ago, Linux server always appeared more heavy but since 2 updates game is completely unplayable and laggy.

**Comment by DeathByKorea** [comment] 2018-02-26 14:24
Can't reproduce on my Linux box, server usage stays below 10% at all times.

**Comment by UserR00T** [comment] 2019-06-24 11:15
Cannot reproduce, closing.

**Closed by UserR00T** 2019-06-24 11:15 UTC
Labels: !Bug, !MAJOR, Server
