### ISSUE TITLE
Blood splatters can be seen through the void

### ISSUE THREAD

**Issue by Ternzeeh** [broke-protocol/BrokeProtocol#105] opened 2017-07-16 12:00 UTC
Whenever a blood splatter is produced from the overworld (outside world of the game), the blood can be seen in the same location but in the void if you are inside a building.

![image](https://user-images.githubusercontent.com/29814492/28247372-75fe31fa-6a61-11e7-91ec-16ec4b14488b.png)

**Comment by BrokeProtocol** [comment] 2017-07-18 02:42
Should be fixed in latest test version 10, need to confirm.

**Comment by BrokeProtocol** [comment] 2017-07-18 19:24
Not fixed.

![bloodsplatter](https://user-images.githubusercontent.com/29849122/28335667-2ab901bc-6bcd-11e7-9aa2-fe6bab9be008.png)

**Comment by BrokeProtocol** [comment] 2018-01-11 09:12
Still problem in 0.72

**Comment by UserR00T** [comment] 2019-06-24 11:52
"this is by design.. keeping splatters and stuff on interiors can cause them to be destroyed if apartments are unloaded."

**Closed by UserR00T** 2019-06-24 11:52 UTC
Labels: !Bug, !Minor, Client, v0.67-prior, vRELEASE
